version: '3'
services:
  db:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db-data:/data/postgres

  web:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: dev.txt
    restart: always
    ports:
      - 8001:8001
    env_file: .env
    command: 'sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8001"'
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  db-data:
