# Generated by Django 3.2.12 on 2022-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='holidays',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='user_geolocation',
            field=models.JSONField(),
        ),
    ]
